name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        S_NAME: ${{ secrets.SERVER_NAME }}
        S_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy with rsync
      shell: bash
      run: |
        sudo apt-get install sshpass
        sshpass -p "$S_PASSWORD" rsync -avze 'ssh -o StrictHostKeyChecking=no' source/* "$S_NAME":~/DiscordHalvaBot/
    - name: Restart bot
      run: sshpass -p "$S_PASSWORD" ssh -o StrictHostKeyChecking=no "$S_NAME" DiscordHalvaBot/restartBot.sh &
